title: Lukas Mateffy
email: hello@mateffy.me
description: >
  I am a young Javascript, PHP and WordPress Developer from Germany. I love to create for the web and mobile space. I run a small design studio: Smoolabs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mateffy.me"
twitter_username: capevace
github_username: capevace

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
  - webpack.mix.js
  - tailwind.config.js
  - README.md
  - package-lock.json
  - mix-manifest.json
  - deploy.sh

collections:
  posts:
    output: true
    permalink: /post/:path
  projects_apps:
    output: true
    permalink: /:path/
    order:
      - convertguru.md
      - hotspot-bypass.md
      - wpls.md
      - woocommerce-shipping-tracker.md
      - mission-control-project.md
      - halbert.md
      - clippo.md
      - playmusic-suite.md
  projects_open_source:
    output: true
    permalink: /:path/
    order:
      - betterpip.md
      - 433mhz.md
      - alpaca.md
  projects_featured:
    output: true
    permalink: /:path/
    order:
      - saufchat.md
      - xen-edit.md
      - alpaca.md
  projects_websites:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "projects_apps"
    values:
      layout: "product"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "projects_open_source"
    values:
      layout: "product"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "projects_featured"
    values:
      layout: "product"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "projects_websites"
    values:
      layout: "product"
